import React, { useState } from 'react';

// The component is now correctly named "VerifyPage"
const VerifyPage = () => {
    const [selectedFile, setSelectedFile] = useState(null);
    const [status, setStatus] = useState('');
    const [downloadUrl, setDownloadUrl] = useState('');

    const handleFileChange = (event) => {
        setSelectedFile(event.target.files[0]);
        setStatus('');
        setDownloadUrl('');
    };

    const handleSubmit = () => {
        if (!selectedFile) {
            setStatus('Please select a JSON file first.');
            return;
        }

        const reader = new FileReader();
        reader.onload = (e) => {
            sendToApi(e.target.result);
        };
        reader.readAsText(selectedFile);
    };

    const sendToApi = (jsonData) => {
        setStatus('Generating certificate, please wait...');
        setDownloadUrl('');

        const apiUrl = 'https://doqccaokp7.execute-api.ap-south-1.amazonaws.com/generate-certificate';

        fetch(apiUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: jsonData
        })
        .then(response => {
            if (!response.ok) {
                throw new Error(`Server error: ${response.statusText}`);
            }
            return response.json();
        })
        .then(data => {
            if (data.download_url) {
                setStatus('Certificate generated successfully!');
                setDownloadUrl(data.download_url);
            } else {
                throw new Error('The response from the server was invalid.');
            }
        })
        .catch(error => {
            console.error('Error:', error);
            setStatus('An error occurred. Please check the console and try again.');
        });
    };

    return (
        <div className="verify-page">
            <style>{`
                .verify-page {
                    min-height: 100vh;
                    font-family: sans-serif;
                    text-align: center;
                    padding: 50px;
                    background-color: #02040a;
                    color: #e6eef3;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    justify-content: center;
                }
                .verify-container { 
                    max-width: 800px; 
                    margin: 0 auto; 
                    padding: 40px 20px; 
                    text-align: center; 
                }
                .verify-title { 
                    font-size: 2.5rem; 
                    font-weight: 800; 
                    margin-bottom: 20px; 
                    color: #e6eef3; 
                }
                .upload-section { 
                    margin-bottom: 30px; 
                }
                .generate-btn { 
                    padding: 14px 24px; 
                    border-radius: 12px; 
                    background: linear-gradient(90deg, #06b6d4, #d946ef); 
                    border: none; 
                    color: #021018; 
                    font-weight: 800; 
                    font-size: 1.1rem; 
                    cursor: pointer; 
                }
                .status-message { 
                    margin-top: 20px; 
                    font-weight: bold; 
                    color: #61dafb; 
                }
                .download-link { 
                    display: inline-block; 
                    margin-top: 20px; 
                    padding: 12px 25px; 
                    font-size: 1.2em; 
                    color: #021018; 
                    background-color: #61dafb; 
                    border-radius: 10px; 
                    text-decoration: none; 
                    font-weight: bold; 
                }
            `}</style>
            
            <div className="verify-container">
                <h1 className="verify-title">Generate Your Wipe Certificate</h1>
                <p style={{color: '#9ca3af', maxWidth: '600px', margin: '0 auto 30px'}}>
                    Upload the JSON file generated by the NullNova tool to create your official, tamper-proof certificate of data destruction.
                </p>

                <div className="upload-section">
                    <input type="file" onChange={handleFileChange} accept=".json" />
                    <button onClick={handleSubmit} className="generate-btn" style={{marginLeft: '10px'}}>Generate PDF</button>
                </div>

                {status && <div className="status-message">{status}</div>}

                {downloadUrl && (
                    <a 
                        href={downloadUrl} 
                        className="download-link"
                        target="_blank" 
                        rel="noopener noreferrer"
                    >
                        Download Your PDF Certificate
                    </a>
                )}
            </div>
        </div>
    );
};

// The component is now correctly exported as "VerifyPage"
export default VerifyPage;
